version: '3.1'
services:
    database:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./database/data:/var/lib/mysql

    php-fpm:
        build:
            context: ./php-fpm
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=8
        volumes:
            - ./app:/var/www

    nginx:
        build:
            context: ./nginx
        volumes:
            - ./app:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - "80:80"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - ./rabbit-mq:/var/lib/rabbitmq:cached
