framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            rabbit_mq: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Message\SmsNotification':  rabbit_mq
