framework:
    messenger:
        transports:
            rabbit_mq:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: emails
                        type: fanout
                    queues:
                        admin_email: ~
                        customer_emails: ~
        routing:
            'App\Message\OrderMessage':  rabbit_mq
